# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
  #output_subdir: ./hrrr/
  job:
    chdir: True
  run:
    dir: /hrrr_out/
    #dir: /coreai_climate_earth2/corrdiff/training_output/
  output_subdir: null

outdir: "./output_regression_hrrr_test"

## Hyperparameters
duration: 200
  # Training duration
batch_size_global: 256
  # Total batch size
batch_size_gpu: 1
  # Limit batch size per GPU
cbase: null  # TODO check
  # Channel multiplier
cres: 1  # TODO check
  # Channels per resolution
lr: 0.0002
  # Learning rate
ema: 0.5
  # EMA half-life
dropout: 0.13
  # Dropout probability
augment: 0.0
  # Augment probability

hr_mean_conditioning: False
  # High-res mean (regression's output) as additional condition
gridtype: "sinusoidal" #"test"
  # can be either linear, sinusoidal, or learnable
N_grid_channels: 4 
  # for pos embedding
grad_clip_threshold: false
  # no gradient clipping for defualt non-patch-based training
lr_decay: 1

P_mean: 0
P_std: 1.2
sigma_data: 0.5

## Performance options
fp_optimizations: amp-bf16
 #amp-bf16
  # Floating point mode, one of ["fp32", "fp16", "amp-fp16", "amp-bf16"]
  # "amp-{fp16,bf16}" activates Automatic Mixed Precision (AMP) with {float16,bfloat16}
ls: 1
  # Loss scaling
bench: false
  # Enable cuDNN benchmarking
workers: 4
  # DataLoader worker processes
songunet_checkpoint_level: 1 # 0 means no checkpointing
  # Gradient checkpointing level, value is number of layers to checkpoint

## I/O-related options
checkpoint_dir: checkpoints
  # Where to save the checkpoints
wandb_mode: disabled
  # Wights & biases mode [online, ofline, disabled]
tick: 1
  # How often to print progress
dump: 50 #500
  # How often to dump state
seed: null  # TODO check
  # Random seed
transfer: null  # TODO check
  # Transfer learning from network pickle
dry-run: false
  # Print training options and exit
use_tf32: true
## Weather data options
dataset:
  type: "twc_mvp1"
  ds_factor: 4
  train: True
  train_years: [2020, 2021, 2022, 2023,]
  valid_years: [2024]
  hrrr_window: [[1,1057], [4,1796]] # need dims to be divisible by 16 [[0,1024], [0,1024]]
  sample_shape: null #[1024, 1024] # 1024,1024 w/ 1 batch 4 hrrr channels and all era5 channels is 77gb
