# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# v0.2
# reslossv2_pmean_neg1.2_allyears
hydra:
  job:
    chdir: True

defaults:
  - train_hrrr
  - _self_ 
  
# batch_size_global: 256
## Main options
outdir: "./diffusion_hrrr_all_years"   
  # Where to save the results
arch: ddpmpp-cwb
  # Network architecture [ddpmpp, ddpmpp-cwb, ncsnpp, adm, ddpmpp-cwb-v0-regression]
precond: reslossv2
  # Preconditioning & loss function [vp, ve, edm, unetregression, resloss]
task: diffusion
  # Which model to train [regression, diffusion]
regression_checkpoint_path: "/coreai_climate_earth2/dpruitt/runs/hrrr_out/regression_hrrr_all_years2/training-state-regression-000514.mdlus"
  # Where to save the checkpoints

dump: 150
songunet_checkpoint_level: 4
dataset:
  #era5_channels: ['u10m', 'v10m', 't2m', 'tcwv', 'sp', 'msl', 'u1000', 'u850', 'u500', 'u250', 'v1000', 'v850', 'v500', 'v250', 'z1000', 'z850', 'z500', 'z250', 't1000', 't850', 't500', 't250', 'q1000', 'q850', 'q500', 'q250']
  in_channels: ['u10m', 'v10m', 't2m', 'tcwv', 'sp', 'msl', 'u1000', 'u850', 'u500', 'u250', 'v1000', 'v850', 'v500', 'v250', 'z1000', 'z850', 'z500', 'z250', 't1000', 't850', 't500', 't250', 'q1000', 'q850', 'q500', 'q250']
  use_all: True
  hrrr_window: [[1,1057], [4,1796]] # need dims to be divisible by 16 [[0,1024], [0,1024]]
  sample_shape: null #[1024, 1024] # 1024,1024 w/ 1 batch 4 hrrr channels and all era5 channels is 77gb
